#!/bin/sh

for i in $@;
do
    if [ "$i" = "-m" ];
    then
        move_files=1
        shift
    fi
done

ACTION="cp"

[ ! -z "$move_files" ] && echo "Shall move" && ACTION="mv"

PATTERN="${1}"
[ -z "${PATTERN}" ] && PATTERN="*.*"

k=1

for i in `ls ${PATTERN}*`;
do
	name="$(sha1sum $i)"
	echo -ne "$k: "; $ACTION -vi "$i" "${name%% *}.${i##*.}"
	k=$(( $k + 1 ))
done
