#!/bin/sh

[ -z "$DIGESTTOOL" ] && DIGESTTOOL="md5sum"

PATTERN="${1}"
[ -z "${PATTERN}" ] && PATTERN="*.*"

k=1

for i in `ls ${PATTERN}*`;
do
	name="$($DIGESTTOOL $i)"
	echo -ne "$k: "; cp -vi "$i" "${name%% *}.${i##*.}"
	k=$(( $k + 1 ))
done
